name: fixit
description: "A new Flutter project."
publish_to: "none" # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  image_picker: ^0.8.4+4
  provider: ^6.0.2
  fluttertoast: ^8.2.1
  google_sign_in: ^5.0.0
  uuid: ^3.0.7
  cupertino_icons: ^1.0.8
#  dialogflow_flutter: ^1.0.0
  http: ^1.0.0
  bubble: ^1.2.1
  flutter_animate: ^4.5.2
  mailer: ^6.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/FixIt.png"
  min_sdk_android: 21 # Android min SDK version
  web:
    generate: true
    image_path: "assets/FixIt.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/FixIt.png"
    icon_size: 48 # Min:48, Max:256, Default:48
  macos:
    generate: true
    image_path: "assets/FixIt.png"
  remove_alpha_ios: true

flutter:
  assets:
    - assets/default_profile.png
    - assets/Google.png
  uses-material-design: true

